### ISSUE TITLE
Disabling send button causes import statement to fail

### ISSUE THREAD

**Issue by supermii2** [nus-cs2103-AY2324S1/forum#148]
Below is my code, and it currently runs smoothly. Why does adding the commented out line under handleUserInput (sendButton.setDisabled(true)) cause the following error? I cannot see why an unrelated line of code would cause an import error.

IDE is IntelliJ

error: package rock.client does not exist
import rock.client.Rock;

```package rock.ui;

import rock.client.Rock;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.TextField;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;
import javafx.scene.layout.Region;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;

public class Gui extends Application {
    private ScrollPane scrollPane;
    private VBox dialogContainer;
    private TextField userInput;
    private Button sendButton;
    private Scene scene;
    private Image user = new Image(this.getClass().getResourceAsStream("/images/DaUser.png"));
    private Image duke = new Image(this.getClass().getResourceAsStream("/images/DaDuke.png"));
    private Rock rock;
    @Override
    public void start(Stage stage) {
        this.rock = new Rock();

        scrollPane = new ScrollPane();
        dialogContainer = new VBox();
        scrollPane.setContent(dialogContainer);

        userInput = new TextField();
        sendButton = new Button("Send");

        AnchorPane mainLayout = new AnchorPane();
        mainLayout.getChildren().addAll(scrollPane, userInput, sendButton);

        scene = new Scene(mainLayout);

        stage.setScene(scene);
        stage.show();

        stage.setTitle("Duke");
        stage.setResizable(false);
        stage.setMinHeight(600.0);
        stage.setMinWidth(400.0);

        mainLayout.setPrefSize(400.0, 600.0);

        scrollPane.setPrefSize(385, 535);
        scrollPane.setHbarPolicy(ScrollPane.ScrollBarPolicy.NEVER);
        scrollPane.setVbarPolicy(ScrollPane.ScrollBarPolicy.ALWAYS);

        scrollPane.setVvalue(1.0);
        scrollPane.setFitToWidth(true);

        dialogContainer.setPrefHeight(Region.USE_COMPUTED_SIZE);

        userInput.setPrefWidth(325.0);

        sendButton.setPrefWidth(55.0);

        AnchorPane.setTopAnchor(scrollPane, 1.0);

        AnchorPane.setBottomAnchor(sendButton, 1.0);
        AnchorPane.setRightAnchor(sendButton, 1.0);

        AnchorPane.setLeftAnchor(userInput , 1.0);
        AnchorPane.setBottomAnchor(userInput, 1.0);

        sendButton.setOnMouseClicked((event) -> {
            handleUserInput();
        });

        userInput.setOnAction((event) -> {
            handleUserInput();
        });

        dialogContainer.heightProperty().addListener((observable) -> scrollPane.setVvalue(1.0));


    }
    private Label getDialogLabel(String text) {
        Label textToAdd = new Label(text);
        textToAdd.setWrapText(true);

        return textToAdd;
    }
    private void handleUserInput() {
        Label userText = new Label(userInput.getText());
        String response = getResponse(userInput.getText());
        if (rock.isTerminated()) {
            userInput.setDisable(true);
            //sendButton.setDisable(true);
        }
        Label dukeText = new Label(response);
        dialogContainer.getChildren().addAll(
                DialogBox.getUserDialog(userText, new ImageView(user)),
                DialogBox.getDukeDialog(dukeText, new ImageView(duke))
        );
        userInput.clear();
    }

    private String getResponse(String input) {
        return rock.getResponse(input);
    }
}

**Comment by damithc** [comment]
@supermii2 I recommend that you push the code to a branch in your fork and share the branch name here so that other can try to replicate the exact problem (or do a more thorough examination of the code).

Your post seems to have some formatting errors -- you can try to fix that too.

**Comment by supermii2** [comment]
Thank you Prof, I've amended the Help Request.

I've pushed my code to this branch. https://github.com/supermii2/ip/tree/A-CodeQuality

I believe it is an IDE issue because even adding a comment to gui.java creates an error

**Comment by damithc** [comment]
@supermii2 While waiting for inputs from others, here are some things you can try:
  * Choose `File` -> `Invalidate caches`
  * Close Intellij -> Delete the `.idea` folder -> Re open the project in Intellij
  * Clone the fork to a different location and open the project in Intellij again to get a fresh start without losing changes you did so far.

**Comment by supermii2** [comment]
Hi prof, thank you for your advice!

The first two didn't work but cloning the fork into a different location works! It was likely an issue with IntelliJ

**Comment by supermii2** [comment]
My bad, I had opened the wrong project. The cloned fork still gives the same error unfortunately.

**Comment by SungMatt** [comment]
It really is a strange problem. I see that you've made it into its own function -- does the problem still exist then?

**Comment by supermii2** [comment]
The problem still existed after making it into its own function, but the issue seemed to be a problem with the gradle? Rebuilding it through gradle (instead of using IntelliJ) seemed to fix it for now...
