### ISSUE TITLE
Smoke Test: Help requested to test program on Mac

### ISSUE THREAD

**Issue by WZWren** [nus-cs2103-AY2324S1/forum#170]
Hi all, I am requesting for help to test my program for Mac - I am facing a similar issue to #164 and I would appreciate it if more people could help me test my app on their Mac.

My program can be found [here](https://github.com/WZWren/ip/releases/tag/A-Release).

EDIT: Here's the image I received on the error, for context:
![Untitled](https://github.com/nus-cs2103-AY2324S1/forum/assets/115881359/747b6ef9-9381-43e3-905e-88b7b7aca908)

**Comment by AlagappanRa** [comment]
Is this a cross-platform issue that you are facing? (Developed on Windows/Linux but distribution on Mac failed?)
You could refer to #159 and try modifying your build gradle before packaging the jar file. 

Or this is problem faced on your local Macbook? (My guess would be this)
You could refer to #118 (Java fx runtime components missing...)

**Comment by WZWren** [comment]
It's a cross-platform issue, I had built it on Windows but distribution on a single Mac had failed.

**Comment by woojiahao** [comment]
I was digging around the OpenJFX documentation and found this section that complements the second method of importing JavaFX for Gradle. Maybe you can try testing this out?

![Screenshot 2023-09-22 at 08 53 43](https://github.com/nus-cs2103-AY2324S1/forum/assets/29497029/eaf9bb9a-fd6d-429e-a44d-5a4d20960a61)

**Comment by WZWren** [comment]
> I was digging around the OpenJFX documentation and found this section that complements the second method of importing JavaFX for Gradle. Maybe you can try testing this out?

@woojiahao Forgive me for being out of the loop here, but I don't really understand what you mean by "second method of importing JavaFX into gradle". Was there a section that I had missed on the site? I had followed the JavaFX tutorial [here](https://se-education.org/guides/tutorials/javaFxPart1.html) so I am unaware about a second method.

**Comment by woojiahao** [comment]
Oh seems like prof removed it because it was causing so many problems. There was a secondary method to install JavaFX on Gradle

**Comment by revdrag** [comment]
I faced a similar issue when I tried to distribute my Jar file to a friend using Mac (built on Windows, but unable to run on mac). I believe the issue is with the version of the javafx gradle plugin as brought up by in the Openjfx forum [here](https://github.com/openjfx/javafx-gradle-plugin/issues/112). It seems like the issue with the Gradle plugin was fixed in openjfx version 0.0.13, maybe we could have a hotfix after verifying that is the issue.

For now, I tweaked my build.gradle dependencies to declare the `mac-aarch64` architecture and it was able to run on my friend's mac. You can try this and let us know how it goes!

```
dependencies {
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.10.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.10.0'

    String javaFxVersion = '17.0.7'

    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac-aarch64'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac-aarch64'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac-aarch64'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac-aarch64'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'
}
```

**Comment by damithc** [comment]
> Oh seems like prof removed it because it was causing so many problems. There was a secondary method to install JavaFX on Gradle

Yup, removed it yesterday.

**Comment by woojiahao** [comment]
Hi prof @damithc , I may have found a potential fix for this issue, I've created a tips issue #173 and am trying to run the JAR on other platforms. So far, the fix works on Mac and Windows (both ARM and x86)

**Comment by WZWren** [comment]
OK, so it seems like this was a Java version issue - the Mac that this was tested on was not the one given in the advisory, and due to some miscommunication, we had thought that changing the version did not fix the issue when it in fact it had fixed it.

One interesting thing that had arose here though was that the tester was using Java Launcher to test the jar files - from what I can see Java Launcher could only test 1 of the 3 jar files she was supplied with from different iP projects, but the other 2 jar files could only be launched without error from the terminal using `java -jar nameOfJar.jar`.

The only major difference I could see in the build.gradle files for that jar file compared to the other 2 was the inclusion of the `checkstyle` module (possibly related to [this](https://github.com/nus-cs2103-AY2324S1/forum/issues/159#issuecomment-1729226821)). The 2 jar files that failed to run had the `checkstyle` module configured while the 1 that ran did not have it at all.

While the errors have been resolved, I would still appreciate if additional people could test if they can open the program on Mac to confirm if the program can run on the OS.
